name: Version and Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write
  pull-requests: write

jobs:
  version:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./site
    outputs:
      published: ${{ steps.manual-version.outputs.published }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Install dependencies
        run: pnpm install

      - name: Check for changesets
        id: check-changesets
        run: |
          if [ -d ".changeset" ] && [ "$(ls -A .changeset)" ]; then
            echo "has-changesets=true" >> $GITHUB_OUTPUT
          else
            echo "has-changesets=false" >> $GITHUB_OUTPUT
          fi

      - name: Version packages
        if: steps.check-changesets.outputs.has-changesets == 'true'
        run: |
          echo "Before version bump:"
          cat package.json | grep version
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          pnpm changeset version
          echo "After version bump:"
          cat package.json | grep version
          git add .
          git commit -m "chore: version packages" || exit 0
          git push
          echo "Pushed commit:"
          git log --oneline -1
          echo "published=true" >> $GITHUB_OUTPUT
          echo "new-version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
        id: manual-version

  build:
    needs: version
    if: needs.version.outputs.published == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0
      
      - name: Pull latest changes
        run: git pull origin main
      
      - name: Debug - Check version before build
        run: |
          echo "Current commit:"
          git log --oneline -1
          echo "Package.json version:"
          cd site
          cat package.json | grep version
          node -p "require('./package.json').version"
      
      - name: Install, build, and upload your site
        uses: withastro/action@v2
        with:
          path: ./site
          node-version: 22
          package-manager: pnpm@latest

  deploy:
    needs: build
    if: needs.version.outputs.published == 'true'
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4